// Generated by https://quicktype.io

import { Cargo } from "./cargo";
import { Dependencia } from "./dependencia";

export interface CargoXDependencia {
    id:                number;
    cargoId:           number;
    dependenciaId:     number;
    _Cargo:            Cargo;
    _Dependencia:      Dependencia;
}
