// Generated by https://quicktype.io

import { PreguntasCerradas } from "./pregunta_cerradas";

export interface Dimension {
    id:                 number;
    nombre:             string;
    instrumentoId:      number;
    preguntasCerradas?: PreguntasCerradas[];
}

