// Generated by https://quicktype.io

import { Pregunta } from "./pregunta";

export interface Dimension {
    id:                number;
    nombre:            string;
    instrumentoId:      number;
    preguntas?:         Pregunta[];
}

export interface DimensionView {
    id:                number;
    nombre:            string;
    tipoEntidadId:     number;
    tipoEntidad:       null;
    preguntas?:         Pregunta[];
}
