// Generated by https://quicktype.io

export interface Escala {
    id:                            number;
    nombre:                        string;
    simbologia:                    string;
    valoracion:                    number;
    nivelCumplimiento:             string;
    eliminado:                     boolean;
    visible:                       boolean;
    idUsuarioCreador?:              string,
    idUsuarioModifica?:             string,
    idUsuarioElimina?:              string
}

export type post = 'post' | 'update';