// Generated by https://quicktype.io

import { Cargo } from "./cargo";

export interface EvaluacionCargo {
    id:                number;
    cargoEvaluadorId:  number;
    cargoId:           number;
    cantidadEvaluados: number;
    cargo?:            Cargo;
}