// Generated by https://quicktype.io

import { Dimension } from "./dimension";

export interface Instrumento {
    id:                   number;
    nombre:               string;
    tipoEvaluacionId:     number;
    tipoTrabajadorId:       number;
    dimensiones?:         Dimension[];
    habilitar?:            boolean;
}
export type tipoModal =  'add' | 'edit'
export type postDelete =  'instrumento' | 'dimension'

