// Generated by https://quicktype.io

import { Type } from "@angular/core";
import { Dimension } from "./dimension";

export interface Instrumento {
    id:                   number;
    nombre:               string;
    tipoEntidadId:        number;
    tipoEvaluacionId:     number;
    dimensiones?:          Dimension[];
}
export type tipoModal =  'add' | 'edit'

// Generated by https://quicktype.io

