// Generated by https://quicktype.io

import { Type } from "@angular/core";

export interface Instrumento {
    id:                   number;
    nombre:               string;
    tipoEntidadId:        number;
    tipoEvaluacionId:     number;
}

export enum tipoPregunta {
    open = "Abierta",
    closed = "Cerrada"
}