// Generated by https://quicktype.io

export interface Modulo {
    id:                number;
    titulo:            string;
    descripcion:       string;
    path:              string;
    loadComponent:     string;
    imgLocation:       string;
    subModulos:        null;
}
