// Generated by https://quicktype.io

export interface Periodo {
    id:                   number;
    nombre:               string;
    fechaInicio:          string;
    fechaFin:             string;
}
