// Generated by https://quicktype.io

import { Instrumento } from "./instrumento";
import { Periodo } from "./periodo";

export interface PeriodoxInstrumento {
    periodoId:         number;
    instrumentoId:     number;
    periodo?:           Periodo;
    instrumento?:       Instrumento;
}
