// Generated by https://quicktype.io

import { RespuestaCerrada } from "./RespuestaCerrada.interface";



export interface PreguntasCerradas {
    id:                number;
    nombre:            string;
    dimesionId:        number;
    respuestasCerradas?: RespuestaCerrada[];
}