// Generated by https://quicktype.io

export interface Pregunta {
    id:                number;
    nombre:            string;
    instrumentoId:     number;
    tipoPreguntaId:    number;
    dimesionId:        number;
}

