// Generated by https://quicktype.io

export interface SubModulo {
    id:                number;
    titulo:            string;
    descripcion:       string;
    path:              string;
    loadComponent:     string;
    moduloId:          number;
    eliminado:         boolean;
}
