// Generated by https://quicktype.io

export interface TipoEvaluacion {
    id:                number;
    nombre:            string;
    descripcion:       string;
    eliminado:         boolean;
    visible:           boolean;
}
