export interface TipoEntidad
{
    id: number,
    nombre: string
}

// Generated by https://quicktype.io

export interface TipoTrabajador {
    id:                number;
    nombre:            string;
    icono:             null;
    instrumentos?:     null;
}
